import re, json

NEW = [
 # --- Existing tracked shipments (statuses refreshed for Jul 2) ---
 {"id":"SHP-001","mfg":"RENO Lighting","so":"S091325","po":"5303","ship":"2026-06-12","carrier":"CCT","tracking":"MISSING","exp":"2026-06-19","status":"Delivered","desc":"RENO fixtures — shipped Jun 12 (CCT, ETA 7 days). ETA elapsed; presumed delivered. Note: SO S091325/PO 5303 is a recurring stock SO — reshipped again Jun 26 (see SHP-023).","job":"Store 9 / Stock","flag":"Presumed delivered (ETA+, no carrier tracking #/GIT receipt); confirm with GIT"},
 {"id":"SHP-002","mfg":"RENO Lighting","so":"S088807","po":"5251","ship":"2026-06-16","carrier":"Western Canada Express","tracking":"WC991057","exp":"2026-06-22","status":"Delivered","desc":"THE VUE order (Type L/M/Q/S, R31101/R31041) — shipped Jun 16 (WCE, ETA 7-9). GIT confirmed receipt Jun 22: 'WCE delivered three pallets from Reno.' Final partial for S088807.","job":"THE VUE","flag":""},
 {"id":"SHP-003","mfg":"RENO Lighting","so":"S094971","po":"5389","ship":"2026-06-11","carrier":"Vitran","tracking":"MISSING","exp":"2026-06-26","status":"Delivered","desc":"777 Hornby — RENO 'S094971 / PO 5389 shipped' (Jun 11, Vitran). Earlier misrouted to Powell River, rerouted ~Jun 18. GIT confirmed receipt Jun 26: 'Vitran delivered a pallet from Reno.' DELIVERED.","job":"777 Hornby","flag":""},
 {"id":"SHP-004","mfg":"Kuzco","so":"C-ORD00067537","po":"5299","ship":"2026-06-10","carrier":"K&H LTL","tracking":"4831380","exp":"2026-06-17","status":"Delivered","desc":"PARK PLACE LOBBY — custom Kuzco PD88160-BK (via Nuvo Sales), shipped Jun 10 (K&H LTL, tracking 4831380). ETA elapsed; delivered.","job":"PARK PLACE LOBBY","flag":""},
 {"id":"SHP-005","mfg":"CNA Lighting","so":"","po":"","ship":"2026-06-10","carrier":"Local pickup (Burnaby)","tracking":"","exp":"2026-06-12","status":"Delivered","desc":"CNA bankcard order #061026 placed Jun 10 ($1,630.91); CNA invoice 51763 issued. Local pickup order — presumed picked up/closed.","job":"Canucks - Rogers Arena","flag":""},
 {"id":"SHP-006","mfg":"RENO Lighting","so":"S089014","po":"5266","ship":"2026-06-17","carrier":"Western Canada Express","tracking":"","exp":"2026-06-17","status":"Delivered","desc":"GIT receipt Jun 17 — WCE delivered Reno pallet (Ravenna 7\" SM). Labeled MARCON - RAVENNA at warehouse.","job":"MARCON - RAVENNA","flag":""},
 {"id":"SHP-007","mfg":"RENO Lighting","so":"","po":"","ship":"2026-06-15","carrier":"Western Canada Express","tracking":"","exp":"2026-06-15","status":"Delivered","desc":"GIT receipt Jun 15 — 8ft pallet from Reno delivered to warehouse.","job":"Unspecified (Reno)","flag":"No SO/PO on GIT receipt — tag at warehouse to identify job"},
 {"id":"SHP-008","mfg":"RENO Lighting","so":"","po":"","ship":"2026-06-01","carrier":"Western Canada Express","tracking":"","exp":"2026-06-01","status":"Delivered","desc":"GIT receipt Jun 1 — WCE delivered Reno pallet (Ark Halo series). 48x40x85\", 295 lbs. Picked up by Urban Valley.","job":"Unspecified (Reno Ark Halo)","flag":"No SO/PO on GIT receipt — identify job"},
 {"id":"SHP-009","mfg":"RENO Lighting","so":"S094264","po":"5367","ship":"2026-05-25","carrier":"Western Canada Express","tracking":"1252480110","exp":"2026-06-03","status":"Delivered","desc":"BAPTIST HOUSING SAMPLES — shipped May 25 (WCE, ETA 8-9); tracking 1252480110. ETA elapsed.","job":"BAPTIST HOUSING SAMPLES","flag":""},
 {"id":"SHP-010","mfg":"RENO Lighting","so":"S094536","po":"5374","ship":"2026-05-29","carrier":"Purolator (Small Parcel)","tracking":"MISSING","exp":"2026-06-05","status":"Delivered","desc":"BCNPH M&C Samples — shipped May 29 (Purolator, ETA 5-7). Delivered.","job":"BCNPH M&C Samples","flag":""},
 {"id":"SHP-011","mfg":"RENO Lighting","so":"S094828","po":"5381","ship":"2026-06-05","carrier":"Purolator (Small Parcel)","tracking":"MISSING","exp":"2026-06-11","status":"Delivered","desc":"SOF 7823 — shipped Jun 5 (Purolator, ETA 5-6). Delivered.","job":"SOF 7823","flag":""},
 {"id":"SHP-012","mfg":"RENO Lighting","so":"S094832","po":"5383","ship":"2026-06-09","carrier":"UPS","tracking":"MISSING","exp":"2026-06-15","status":"Delivered","desc":"SHAPE UPTOWN 8\" POTS — shipped Jun 9 (UPS, ETA 4-6). Delivered.","job":"SHAPE UPTOWN 8\" POTS","flag":""},
 {"id":"SHP-013","mfg":"Kuzco","so":"C-ORD00075625","po":"4086-R","ship":"2026-06-11","carrier":"LoomisGround","tracking":"LSHP49591980","exp":"2026-06-12","status":"Delivered","desc":"Kuzco shipment 4086-R — shipped Jun 11, est. delivery Jun 12. Warranty/replacement.","job":"Kuzco Warranty / Replacement","flag":"Job not confirmed — verify which project this replacement belongs to"},
 {"id":"SHP-014","mfg":"RENO Lighting","so":"S095362","po":"5399","ship":"","carrier":"","tracking":"MISSING","exp":"","status":"Order Placed","desc":"MARCON RAVENNA 7\" SM — PO issued to RENO Jun 17; order confirmed. No ship notice yet as of Jul 2.","job":"MARCON RAVENNA 7\" SM","flag":"Order placed/confirmed Jun 17 — 15 days, no ship notice; follow up with RENO for ETA"},
 {"id":"SHP-015","mfg":"RENO Lighting","so":"","po":"","ship":"2026-06-22","carrier":"Storm Electric (internal drop-off)","tracking":"","exp":"2026-06-22","status":"Delivered","desc":"GIT receipt Jun 22 — Storm Electric dropped off (2) 8ft Reno boxes at warehouse.","job":"Unspecified (Reno 8ft via Storm)","flag":"No SO/PO on GIT receipt — tag at warehouse to identify job"},
 {"id":"SHP-016","mfg":"RENO Lighting","so":"S095544","po":"5405","ship":"2026-06-25","carrier":"RENO (carrier TBD)","tracking":"MISSING","exp":"2026-07-02","status":"Due Today","desc":"RENO SO# S095544 / PO# 5405 — confirmed Jun 23; RENO invoice IN101083 issued Jun 25 (RENO invoices on shipment), presumed shipped Jun 25. ETA ~Jul 2. May correspond to a GIT Reno pallet receipt (Jun 25/26) — confirm.","job":"Unspecified (RENO PO 5405)","flag":"ETA today; no carrier/tracking on file — confirm GIT receipt + identify job"},
 {"id":"SHP-017","mfg":"RENO Lighting","so":"S095542","po":"5393","ship":"2026-06-25","carrier":"RENO (carrier TBD)","tracking":"MISSING","exp":"2026-07-02","status":"Due Today","desc":"RENO SO# S095542 / PO# 5393 — confirmed Jun 23; invoice IN101084 Jun 25, partial presumed shipped. PARTIAL: only 62x R39208 in stock shipped; remainder backordered to 2026-07-15.","job":"Unspecified (RENO PO 5393)","flag":"ETA today; partial (balance backordered Jul 15). No carrier/tracking — confirm receipt + identify job"},
 {"id":"SHP-018","mfg":"Advant Lighting","so":"","po":"5404","ship":"2026-06-23","carrier":"Green Image Tech (local)","tracking":"","exp":"2026-06-23","status":"Delivered","desc":"MHOND CEILING ADVANT — Hazel 275 E 14th Ave. PO 5404 to GIT. GIT confirmed 'ready for pickup. Four boxes.' Jun 23.","job":"Hazel 275 E 14th Ave (Mhond)","flag":""},
 {"id":"SHP-019","mfg":"Ortech (via GIT)","so":"","po":"","ship":"2026-06-23","carrier":"Green Image Tech (receipt)","tracking":"","exp":"2026-06-23","status":"Delivered","desc":"GIT receipt Jun 23 — 'a pallet of Ortech products delivered' (packing list attached). Likely Hopehill/Baptist Ortech pots.","job":"Hopehill / Baptist (Ortech)","flag":"Ortech not on approved mfg list — GIT warehouse receipt; confirm job from packing slip"},
 {"id":"SHP-020","mfg":"CSC LED","so":"","po":"","ship":"2026-06-22","carrier":"Local pickup (Burnaby)","tracking":"","exp":"2026-06-22","status":"Delivered","desc":"CSC LED 'Storm 4' Vapour Tight, 3 pcs' — ready for local pickup; invoice 4090877 Jun 23.","job":"Storm Electric","flag":""},
 {"id":"SHP-021","mfg":"EiKO","so":"SO188866","po":"5344","ship":"2026-06-26","carrier":"Day & Ross / carrier per EiKO","tracking":"A11182767-0001 / -0002","exp":"2026-07-03","status":"In Transit","desc":"EiKO PO 5344 / SO188866 (CF - 200 BURRARD EIKO). Ship notices re-issued Jun 26 & Jun 30; EiKO invoices Jun 26/29. Ship-to: Fully Loaded / Richmond Storage. In transit; ETA ~Jul 3.","job":"CF - 200 Burrard (EiKO)","flag":"EiKO not on approved mfg list — confirmed inbound PO w/ tracking; confirm delivery"},
 {"id":"SHP-022","mfg":"Onlumi (Shenzhen)","so":"","po":"","ship":"2026-06-25","carrier":"DHL","tracking":"7754899854","exp":"2026-07-02","status":"Due Today","desc":"Onlumi LED strip/connector order — payment/FX wire Jun 24; DHL Jun 25 (AWB 7754899854). DHL support-doc/customs email Jun 26. ETA ~Jul 2.","job":"Unspecified (Onlumi strip/connectors)","flag":"Onlumi not on approved mfg list — international DHL; clear customs, confirm delivery, assign to job/stock"},
 {"id":"SHP-023","mfg":"RENO Lighting","so":"S091325","po":"5303","ship":"2026-06-26","carrier":"Western Canada Express","tracking":"MISSING","exp":"2026-07-06","status":"In Transit","desc":"Store 9 / Stock — RENO SO# S091325 / PO# 5303 reshipped Jun 26 (WCE, ETA 7-8). Recurring stock SO. Latest partial in transit.","job":"Store 9 / Stock","flag":"No carrier tracking # on ship notice — request WCE PRO from RENO"},
 {"id":"SHP-024","mfg":"RENO Lighting","so":"","po":"","ship":"2026-06-25","carrier":"Western Canada Express","tracking":"","exp":"2026-06-25","status":"Delivered","desc":"GIT receipt Jun 25 — 'WCE delivered a pallet from Reno' (packing slip attached). Warehouse arrival.","job":"Unspecified (Reno)","flag":"No SO/PO on GIT receipt — tag to identify job/PO"},
 {"id":"SHP-025","mfg":"Nedco West Canada","so":"5974859","po":"5406","ship":"","carrier":"Ships to site (via RENO)","tracking":"MISSING","exp":"2026-07-15","status":"Order Placed","desc":"MAPLE TOWERS - NEDCO — PO to Nedco Jun 25; Nedco order 5974859 placed, ships to site as directed. RENO advises R31106 out of stock till Jul 15, R31105 till Aug 31.","job":"Maple Towers","flag":"BACKORDER: R31106 ETA Jul 15, R31105 ETA Aug 31 — decide whether to partial-ship in-stock items"},
 # --- New this refresh (Jun 26–Jul 2) ---
 {"id":"SHP-026","mfg":"Artika (via Design Concepts)","so":"","po":"5408","ship":"2026-07-01","carrier":"carrier TBD (auto tracking)","tracking":"MISSING","exp":"","status":"In Transit","desc":"WOODLANDS ARTIKA EXTRAS TYPE G1 / N — Artika confirmed PO 5408 to fulfillment Jun 26; in stock, ships 2-3 business days, tracking auto-generated. Presumed shipped ~Jul 1.","job":"Woodlands","flag":"Artika not on approved mfg list — confirmed inbound PO; capture auto tracking # + ETA"},
 {"id":"SHP-027","mfg":"CSC LED","so":"4091094","po":"","ship":"2026-06-29","carrier":"CSC prepaid (carrier TBD)","tracking":"MISSING","exp":"2026-07-06","status":"In Transit","desc":"CSC LED order 4091094 — placed Jun 25 (prepay & charge). Ships from Ontario warehouse within 2 biz days, ~5 biz days transit. Invoice 4091094 issued Jun 26. ETA ~Jul 6.","job":"Unspecified (CSC 4091094)","flag":"No tracking # yet — request from CSC (Viviane); identify job"},
 {"id":"SHP-028","mfg":"CSC LED","so":"","po":"5376","ship":"","carrier":"Local pickup (Burnaby)","tracking":"","exp":"","status":"Order Placed","desc":"CSC LED PO 5376 — order ready at CSC; not yet picked up (CSC nudged Jun 26 'hasn't been picked up yet').","job":"Unspecified (CSC PO 5376)","flag":"Ready at CSC — arrange pickup; confirm job"},
 {"id":"SHP-029","mfg":"RENO Lighting","so":"","po":"","ship":"2026-06-26","carrier":"Vitran","tracking":"","exp":"2026-06-26","status":"Delivered","desc":"GIT receipt Jun 26 — 'Vitran delivered a pallet from Reno' (packing slip attached). Warehouse arrival. Storm Electric picked up some boxes from this delivery Jun 26.","job":"Unspecified (Reno via Vitran)","flag":"No SO/PO on GIT receipt — tag to identify job/PO"},
 {"id":"SHP-030","mfg":"Kuzco","so":"","po":"","ship":"","carrier":"","tracking":"MISSING","exp":"","status":"Order Placed","desc":"WOODLANDS EXTRA KUZCO TYPE N3, R3 — PO to Kuzco (via Nuvo Sales) Jun 25; Sharon confirmed 'PO received & entered.' Kuzco invoice C-INV00103380 ($3,061.91) Jun 29. Awaiting ETA.","job":"Woodlands","flag":"PO entered Jun 25 — request ETA/ship confirmation from Nuvo/Kuzco"},
 {"id":"SHP-031","mfg":"Lotus","so":"","po":"","ship":"","carrier":"Local pickup (Delta)","tracking":"","exp":"","status":"Order Placed","desc":"BAPTIST SAMPLING LOTUS R1 — Lotus confirmed 1 sample processed for pickup in Delta Jun 30 (case-qty item reduced to single sample).","job":"BAPTIST HOUSING SAMPLES","flag":"Ready for pickup at Lotus Delta warehouse — arrange pickup"},
]

with open("build_dashboard.py","r",encoding="utf-8") as f:
    src=f.read()

start=src.index("shipments = [")
end=src.index("\n]\n",start)+len("\n]\n")
block="shipments = "+json.dumps(NEW, indent=4)+"\n"
src=src[:start]+block+src[end:]
src=src.replace('HTML = HTML.replace("__LAST_UPDATED__", "Jun 26, 2026")','HTML = HTML.replace("__LAST_UPDATED__", "Jul 2, 2026")')

with open("build_dashboard.py","w",encoding="utf-8") as f:
    f.write(src)
print("patched OK; shipments:",len(NEW))
